### ISSUE TITLE
vcf2bed segmentation fault

### ISSUE THREAD

**Issue by ZhenyuZ** [zwdzwd/biscuit#22]
I followed the instructions to use biscuit 0.2.2.20170522 for alignment and so on using a 58GB TCGA WGBS file. I repeatedly got segmentation fault at vcf2bed step

biscuit vcf2bed -k 10 -t cg output.vcf.gz > output.cg.bed

job killed when the output is about 42Mb. I have tried small input and have no problems. 

Btw, I assume I can chunk the input VCF to smaller ones and get the same result after merging the output. Could you confirm this?

**Comment by chrisamiller** [comment]
I'm also seeing this happen on a large subset of WGBS samples (perhaps 25%).  I'm consistently getting segfaulting in the middle of vcf2bed runs on large pileup.vcf.gz files from the biscuit pipeline.   I can provide example files (though they're quite large) if needed.

**Comment by zwdzwd** [comment]
I think a lot has been updated since last year. Could you provide me the version number of biscuit you are using? Thanks.

**Comment by chrisamiller** [comment]
I'm using version 0.2.2.20170522, which I see is not the latest release.  I'll try the latest version, and I'll report back tomorrow

**Comment by chrisamiller** [comment]
New version seems to solve the problem - this can be resolved.  Thanks!

**Comment by ttriche** [comment]
fwiw, if you use samblaster with biscuit, be absolutely certain to use a
version later than 0.3.2


--t

**Comment by zwdzwd** [comment]
Thank you for getting back @chrisamiller . I am glad it worked!
