### ISSUE TITLE
Typo in VCF header causing issues with pyVCF parsing

### ISSUE THREAD

**Issue by aays** [zwdzwd/biscuit#23]
In `biscuit pileup`, a misspelling of Description as 'Desccription' in the output VCF header raises an error when parsing with [pyVCF](https://pyvcf.readthedocs.io/en/latest/). I managed to fix this by directly editing the output VCF myself, but felt it was worth pointing out.

Here is the error raised:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/vcf/parser.py", line 300, in __init__
    self._parse_metainfo()
  File "/usr/local/lib/python3.5/site-packages/vcf/parser.py", line 326, in _parse_metainfo
    key, val = parser.read_filter(line)
  File "/usr/local/lib/python3.5/site-packages/vcf/parser.py", line 143, in read_filter
    "One of the FILTER lines is malformed: %s" % filter_string)
SyntaxError: One of the FILTER lines is malformed: ##FILTER=<ID=PASS,Desccription="All filters passed">
```

And here is the putative cause:
https://github.com/zwdzwd/biscuit/blob/7680b8e28954053bc79297abc3bc983b86a31b44/src/pileup.c#L1379

Thank you for this great tool otherwise!

**Comment by zwdzwd** [comment]
Thanks for pointing out this. This is corrected in the developmental branch and will be updated in the next release.
