### ISSUE TITLE
Precompiled download error

### ISSUE THREAD

**Issue by Irfanwustl** [zwdzwd/biscuit#31]
Is there any problem with the following command? `curl -O $(curl -s https://api.github.com/repos/zwdzwd/biscuit/releases/latest | grep browser_download_url | grep x86_64 | cut -d '"' -f 4)`

My Linux machine is saying : 

> curl: no URL specified!

**Comment by zwdzwd** [comment]
Sorry, should be linux_amd64. changed

`curl -OL $(curl -s https://api.github.com/repos/zwdzwd/biscuit/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d '"' -f 4)`
