### ISSUE TITLE
Conversion Rate calculation

### ISSUE THREAD

**Issue by Irfanwustl** [zwdzwd/biscuit#45]
Hi, 
Thanks for the great tool.

I have used BISCUIT and generated bw and bam files. However, I am trying to calculate the bisulfite conversion rate. Is there any way so that BISCUIT can provide the rate from the aligned bam file? 

Or do I need to write a script? In the aligned bam file, I have found that there are ZC (Number of cytosine conversions) and ZR (Number of cytosine retentions) tags. Probably I need to use those to calculate the rate?

**Comment by jamorrison** [comment]
Hi @Irfanwustl 

BISCUIT is now maintained at [the huishenlab repo](https://github.com/huishenlab/biscuit). If you are still in need of help, please open an issue on that repo's [Issues page](https://github.com/huishenlab/biscuit/issues).

**Comment by Irfanwustl** [comment]
Thanks
